#!/bin/dash


if test -e '.shrug'
then
    echo "$0: error: .shrug already exists"
else
    mkdir .shrug
    mkdir -p .shrug/index
    mkdir -p .shrug/commits
    mkdir -p .shrug/branch
    #printf 'master' > '.shrug/currentBranch'
    echo "" > .shrug/log.txt
    echo "Initialized empty shrug repository in .shrug"
fi



